// ===================================================================
//  Copyright © 2026 Revision Labs and contributors
//  SPDX-License-Identifier: MIT
//  See LICENSE.txt in the project root for full license information.
// ===================================================================

using System;
using System.Security.Cryptography;
using System.Text;
using FluentAssertions;
using Revi;
using Xunit;

namespace ReviDotNet.Tests.Guidance;

/// <summary>
/// Pins RegexAuto output for public Revi contracts to the output generated by
/// Newtonsoft.Json.Schema 4.0.1 at ReviDotNet commit 819d655. These values must not be
/// regenerated during a schema-library migration: a change is a provider-facing compatibility change.
/// </summary>
public sealed class RegexGeneratorPublicContractTests
{
    [Fact]
    public void Object_regex_remains_the_legacy_unconstrained_value_union()
    {
        RegexGenerator.FromObject(typeof(object), chainOfThought: false).Should().Be(
            "(?:\\{\\s*\\s*\\}|\\[\\s*\\s*\\]|\"[^\"]*\"|\\d+|-?\\d+(\\.\\d+)?([eE][+-]?\\d+)?|(true|false))");
    }

    [Theory]
    [InlineData(false, null, 2128, "7EF6E5C687AECBDA47329C9D34B577AB1B4D76836A18850CB7A6948F9132578B")]
    [InlineData(false, "<|eot_id|>", 2140, "A857C0D74CF1232C7450ADD6877972E13B3E6D9E3712716B9E43CAE5D2208BB0")]
    [InlineData(false, ".*stop", 2136, "0E17CE0138E3629FAD58BFAD3A82A13C6240D09DDFDFB576E2F9DB8C5AAA28E5")]
    [InlineData(true, null, 2157, "A15E4C9E589BE566E75172E0C9177BC4802F2206896DD3D199006F81F112BCFF")]
    [InlineData(true, "<|eot_id|>", 2169, "8D444444F34432DD1EF5C8B7F360EDA8C8FC28B12AF9E3777FEE7BADE3B5800B")]
    [InlineData(true, ".*stop", 2165, "52793E25EB26604F50B51E9C49B9A2D5D3E23B2045431A6B2FE0797147C277F7")]
    public void Prompt_regex_remains_byte_for_byte_compatible(
        bool chainOfThought,
        string? stopToken,
        int expectedLength,
        string expectedHash) =>
        AssertLegacyContract(typeof(Prompt), chainOfThought, stopToken, expectedLength, expectedHash);

    [Theory]
    [InlineData(false, null, 287, "8ECF3D5CB6467681F087106E2BCDC2197414167CB6F77A7988AB9138A77CCF8D")]
    [InlineData(false, "<|eot_id|>", 299, "A1A07006D869BF0AE0EB5147F20343A579041856F153C1AB79801B125AEC3D44")]
    [InlineData(false, ".*stop", 295, "7C9D61D9FFD0D42D2EFB968A122CCA4E1F3D7DCDFE56D5788A47CD64CE8B5EE2")]
    [InlineData(true, null, 316, "E6AF9DE6531F6A4EDAC76EF17621DC460C90FA51456C7B9443D1E12C8545C0AE")]
    [InlineData(true, "<|eot_id|>", 328, "EE767DC9B4E766EE5105A5BE08219F9AF725BC4DC0C247D428000BE353226318")]
    [InlineData(true, ".*stop", 324, "5AA49471129F248D21A2399552CD8A6BB63FE7A71F2093E261243BB5431846B4")]
    public void AgentStepResponse_regex_remains_byte_for_byte_compatible(
        bool chainOfThought,
        string? stopToken,
        int expectedLength,
        string expectedHash) =>
        AssertLegacyContract(typeof(AgentStepResponse), chainOfThought, stopToken, expectedLength, expectedHash);

    [Theory]
    [InlineData(typeof(Item), 423, "AC2B29F27850353E729A25F0344A157115D009D2EDE2C03EF1389D06CE1B0AF0")]
    [InlineData(typeof(ComparisonResult), 317, "45CCD318F33F9F358EDA6A9664012D7831C7A95C8871843A611A8FA531A49AE8")]
    public void Object_valued_public_contracts_remain_byte_for_byte_compatible(
        Type type,
        int expectedLength,
        string expectedHash) =>
        AssertLegacyContract(type, chainOfThought: false, stopToken: null, expectedLength, expectedHash);

    [Fact]
    public void AgentStepResponse_base_regex_remains_readably_pinned()
    {
        string regex = RegexGenerator.FromObject(typeof(AgentStepResponse), chainOfThought: false);

        regex.Should().Be("""(?:\{\s*"signal"\s*:\s*(?:"[^"]*"),\s*"tool_calls"\s*:\s*(?:\[\s*(?:\{\s*"name"\s*:\s*(?:"[^"]*"),\s*"input"\s*:\s*(?:"[^"]*")\s*\})(?:\s*,\s*(?:\{\s*"name"\s*:\s*(?:"[^"]*"),\s*"input"\s*:\s*(?:"[^"]*")\s*\}))*?\s*\]),\s*"content"\s*:\s*(?:"[^"]*"),\s*"thinking"\s*:\s*(?:"[^"]*")\s*\})""");
    }

    private static void AssertLegacyContract(
        Type type,
        bool chainOfThought,
        string? stopToken,
        int expectedLength,
        string expectedHash)
    {
        string regex = RegexGenerator.FromObject(type, chainOfThought, stopToken);
        string hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(regex)));

        regex.Should().HaveLength(expectedLength);
        hash.Should().Be(expectedHash);
    }
}
